###
POST http://localhost:9000/api/students HTTP/1.1
Content-Type: application/json

{
    "name": "Luisa Concepcion Salgado",
    "age": "30",
    "active": "1",
    "Order": 3
}

###
GET http://localhost:9000/api/students HTTP/1.1

###
GET http://localhost:9000/api/students/63e1ad646e9901962a5d6182 HTTP/1.1

###

PUT http://localhost:9000/api/students/63eec157771b6e131967f28b HTTP/1.1
Content-Type: application/json

{
    "name": "Luisa Concepcion Salgado",
    "age": 30,
    "active": "1",
    "Order": 6
}
###
DELETE http://localhost:9000/api/students/63e1abaabc73443dab92ce85 HTTP/1.1

###
POST http://localhost:9000/api/classrooms HTTP/1.1
Content-Type: application/json

{
    "Class": "Algebra Lineal",
    "Order": 4,
    "numberOfStudents": 30,
    "active": "1",
    "ListStudents": 4
}


###
GET http://localhost:9000/api/classrooms HTTP/1.1

###
GET http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1

###

PUT http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1
Content-Type: application/json

{
    "Class": "Algebra Lineal",
    "Order": 4,
    "numberOfStudents": 30,
    "active": "0",
    "ListStudents": 4
}

###
DELETE http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1
