###
POST http://localhost:9000/api/students HTTP/1.1
Content-Type: application/json

{
    "name": "Chabelo",
    "age": "89",
    "active": "1"
}

###
GET http://localhost:9000/api/students HTTP/1.1

###
GET http://localhost:9000/api/students/63e1ad646e9901962a5d6182 HTTP/1.1

###

PUT http://localhost:9000/api/students/63e1ad646e9901962a5d6182 HTTP/1.1
Content-Type: application/json

{
    "name": "Xavier Lopez",
    "age": 89,
    "active": "1"
}
###
DELETE http://localhost:9000/api/students/63e1abaabc73443dab92ce85 HTTP/1.1

###
POST http://localhost:9000/api/classrooms HTTP/1.1
Content-Type: application/json

{
    "Class": "Algebra Lineal",
    "Order": 4,
    "numberOfStudents": 30,
    "active": "1",
    "ListStudents": 4
}


###
GET http://localhost:9000/api/classrooms HTTP/1.1

###
GET http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1

###

PUT http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1
Content-Type: application/json

{
    "Class": "Algebra Lineal",
    "Order": 4,
    "numberOfStudents": 30,
    "active": "0",
    "ListStudents": 4
}

###
DELETE http://localhost:9000/api/classrooms/63e1ba8873c4a89a02cc3aad HTTP/1.1
